apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests-limits
  annotations:
    policies.kyverno.io/title: Require Limits and Requests
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      As application workloads share cluster resources, it is important to limit resources
      requested and consumed by each Pod. It is recommended to require resource requests and
      limits per Pod, especially for memory and CPU. If a Namespace level request or limit is specified,
      defaults will automatically be applied to each Pod based on the LimitRange configuration.
      This policy validates that all containers have something specified for memory and CPU
      requests and memory limits.
    pod-policies.kyverno.io/autogen-controllers: none
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-requests
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - armo-system
          - calico-system
          - castai-agent
          - cattle-fleet-system
          - cattle-impersonation-system
          - cattle-system
          - fleet-system
          - flux-system
          - kube-node-lease
          - kube-public
          - kube-system
          - tigera-operator
    preconditions:
      all:
        - key: Job
          operator: AnyNotIn
          value: "{{ request.object.metadata.ownerReferences[].kind }}"
    validate:
      message: "CPU and memory resource requests are required."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"
  - name: validate-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - armo-system
          - calico-system
          - castai-agent
          - cattle-fleet-system
          - cattle-impersonation-system
          - cattle-system
          - fleet-system
          - flux-system
          - kube-node-lease
          - kube-public
          - kube-system
          - tigera-operator
    preconditions:
      all:
        - key: Job
          operator: AnyNotIn
          value: "{{ request.object.metadata.ownerReferences[].kind }}"
    validate:
      message: "CPU and memory resource limits are required."
      pattern:
        spec:
          containers:
          - resources:
              requests:
              limits:
                cpu: "?*"
                memory: "?*"