apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-service-principal
  namespace: cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: gitops-service-principal
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: gitops-service-principal