---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-apps-hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: apps-hub
  source:
    repoURL: https://github.com/hmizael/k8s-stack-example.git
    targetRevision: main
    path: gitops/apps/hub/grafana
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true