---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-nginx-internal-admission
  namespace: ingress-nginx-internal
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: internal
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.6.4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-ingress-nginx
  namespace: ingress-nginx-internal
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: internal
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-ingress-nginx-admission
  namespace: ingress-nginx-internal
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: internal
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: admission-webhook
  annotations:
    argocd.argoproj.io/hook: PreSync,PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded