---
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-ingress-nginx-controller
  namespace: ingress-nginx-internal
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: internal
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
data:
  allow-snippet-annotations: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-ingress-nginx-tcp
  namespace: ingress-nginx-internal
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: internal
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
data: 
  "9200": elk/trimtech-es-default:9200
  "5044": elk/logstash:5044