---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-stack-example
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/hmizael/k8s-stack-example.git