apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: trimtech
  namespace: elk
spec:
  version: 8.8.2
  count: 1
  elasticsearchRef:
    name: trimtech
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: "https://kibana.trimtech.com.br"
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1536"
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 1Gi