---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-infra-tools-aks-hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-tools
  source:
    repoURL: https://github.com/hmizael/k8s-stack-example.git
    targetRevision: main
    path: gitops/infra-tools/aks-hub/cert-manager
    directory:
      directory:
      recurse: false
      include: '*.yaml'
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
      - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")