---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-external-infra-tools-aks-hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-tools
  source:
    repoURL: https://github.com/hmizael/k8s-stack-example.git
    targetRevision: main
    path: gitops/infra-tools/aks-hub/ingress-external
    directory:
      directory:
      recurse: false
      include: '*.yaml'
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true