---
apiVersion: v1
kind: Service
metadata:
  name: external-ingress-nginx-controller
  namespace: ingress-nginx-external
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: external-ingress-nginx-controller-admission
  namespace: ingress-nginx-external
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/component: controller