---
# Source: prometheus/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    component: "server"
    app: prometheus
    release: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "32Gi"