apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-tools-main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-tools
  source:
    repoURL: https://github.com/hmizael/k8s-stack-example.git
    targetRevision: main
    path: gitops/infra-tools
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true