apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  secretName: argocd-secret
  dnsNames:
  - argocd.trimtech.com.br
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-trimtech