---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-webhook
  namespace: "external-secrets"
  labels:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: "v0.7.2"
    external-secrets.io/component: webhook