apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-public
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.13.2
    app: external-dns
    zonetype: public
spec:
  selector:
    matchLabels:
      app: external-dns
      zonetype: public
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/version: 0.13.2
        app: external-dns
        zonetype: public
    spec:
      volumes:
        - name: azure-config-file
          secret:
            secretName: external-dns
      serviceAccountName: external-dns
      containers:
        - name: externaldns-public
          image: registry.k8s.io/external-dns/external-dns:v0.13.2
          args:
            - --log-level=info
            - --log-format=text
            - --interval=1m
            - --source=ingress
            - --policy=upsert-only
            - --registry=txt
            - --txt-owner-id=aks-target
            - --domain-filter=trimtech.com.br
            - --provider=azure
          volumeMounts:
            - name: azure-config-file
              mountPath: /etc/kubernetes
              readOnly: true
          resources: {}
          ports:
            - containerPort: 7979
              name: http
              protocol: TCP
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5