apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/version: 0.13.4
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  refreshInterval: 1h
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: external-dns
  target:
    name: external-dns