---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AppProject utilizado para os armazenar os apps dos projetos de produtos com base Magento.
  sourceRepos:
    - 'https://github.com/hmizael/k8s-stack-example.git'
  destinations:
    - name: 'in-cluster'
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'