apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      tenantId: 714f355d-4a89-4035-b3de-9ee58294ead0
      vaultUrl: https://kv-hub-0.vault.azure.net/
      authSecretRef:
        clientId:
          name: azure-keyvault
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-keyvault
          key: ClientSecret
          namespace: external-secrets