---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: policy-reporter-secret-reader
  namespace: policy-reporter
  labels:
    app.kubernetes.io/name: policy-reporter
    app.kubernetes.io/instance: policy-reporter
    app.kubernetes.io/version: "2.14.2"
    app.kubernetes.io/component: reporting
rules:
- apiGroups: ['']
  resources:
  - secrets
  verbs:
  - get