apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-external
  labels:
    app.kubernetes.io/instance: external
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.6.4
spec:
  finalizers:
  - kubernetes