---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/version: 1.7.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-ingress-nginx
subjects:
  - kind: ServiceAccount
    name: external-ingress-nginx
    namespace: ingress-nginx-external
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-ingress-nginx-admission
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: admission-webhook
  annotations:
    argocd.argoproj.io/hook: PreSync,PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-ingress-nginx-admission
subjects:
  - kind: ServiceAccount
    name: external-ingress-nginx-admission
    namespace: "ingress-nginx-external"