---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-ingress-nginx-controller
  namespace: ingress-nginx-external
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: external
    app.kubernetes.io/version: 1.7.1
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: external
      app.kubernetes.io/component: controller
  minAvailable: 1