---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.trimtech.com.br
  kustomize.buildOptions: --enable-helm
  statusbadge.enabled: "true"
  exec.enabled: "true"
  exec.shells: "bash,sh,ash"
  application.resourceTrackingMethod: annotation
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  users.anonymous.enabled: "false"