---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: kyverno
    app: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
  name: kyverno
spec:
  finalizers:
    - kubernetes