---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:cleanup-controller
  labels:
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/name: kyverno-cleanup-controller
    app.kubernetes.io/instance: kyverno
  namespace: kyverno
rules:
- apiGroups:
    - ''
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
- apiGroups:
    - ''
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - patch
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:leaderelection
  namespace: kyverno
  labels:
    app.kubernetes.io/component: kyverno
    app: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
rules:
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - patch
    - update
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - patch
    - update
    - watch