---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-cleanup-controller
  namespace: kyverno
  labels:
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/name: kyverno-cleanup-controller
    app.kubernetes.io/instance: kyverno
spec:
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/name: kyverno-cleanup-controller
    app.kubernetes.io/instance: kyverno
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-cleanup-controller-metrics
  namespace: kyverno
  labels:
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/name: kyverno-cleanup-controller
    app.kubernetes.io/instance: kyverno
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics-port
  selector:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/name: kyverno-cleanup-controller
    app.kubernetes.io/instance: kyverno
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-svc
  labels:
    app.kubernetes.io/component: kyverno
    app: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
  namespace: kyverno
spec:
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: kyverno
    app.kubernetes.io/name: kyverno
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kyverno-svc-metrics
  labels:
    app.kubernetes.io/component: kyverno
    app: kyverno
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.9.2
  namespace: kyverno
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics-port
  selector:
    app: kyverno
    app.kubernetes.io/name: kyverno
  type: ClusterIP